#!/usr/bin/env python3
"""
Singapore Rain Poem Display Program
Beautifully formats and displays the Singapore rain poem
Generated by AgentOS Studio Strands Backend
"""

import time
import sys

def display_singapore_rain_poem():
    """Display the Singapore rain poem with beautiful formatting"""
    
    poem = """
    "Rain in Singapore"

    Beneath the siren's cry, the sky is drenched,
    Where raindrops dance and paint the city's breath.
    The clouds, a cloak of mist, unspool their song,
    And every street is soaked in tropical song.

    The skyline, a titan of glass and steel,
    Now weeps in silver, its towers aglow.
    The rain, a painter's brush, etches the night—
    A gallery of light, where shadows meet.

    The streets, a tapestry of neon and rain,
    Reflect the world in mirrored, fleeting frames.
    The scent of jasmine, the hum of engines,
    A symphony of life, both wild and tame.

    Here, time dissolves in the storm's embrace,
    A dance of chaos, calm, and quiet grace.
    The rain, a poet, writes the city's soul—
    A paradox of modernity and grace.

    So let the storm carve its silent hymn,
    A testament to Singapore's soul.
    In every drop, a story, a dream—
    A city where the rain is both a guest and friend.
    """
    
    # Print with beautiful formatting
    print("=" * 60)
    print("🌧️  SINGAPORE RAIN POEM 🌧️")
    print("=" * 60)
    print(poem)
    print("=" * 60)
    print("✨ Generated by AgentOS Studio Strands ✨")
    print("=" * 60)

def display_with_typewriter_effect():
    """Display poem with typewriter effect"""
    poem_lines = [
        '"Rain in Singapore"',
        '',
        'Beneath the siren\'s cry, the sky is drenched,',
        'Where raindrops dance and paint the city\'s breath.',
        'The clouds, a cloak of mist, unspool their song,',
        'And every street is soaked in tropical song.',
        '',
        'The skyline, a titan of glass and steel,',
        'Now weeps in silver, its towers aglow.',
        'The rain, a painter\'s brush, etches the night—',
        'A gallery of light, where shadows meet.',
        '',
        'The streets, a tapestry of neon and rain,',
        'Reflect the world in mirrored, fleeting frames.',
        'The scent of jasmine, the hum of engines,',
        'A symphony of life, both wild and tame.',
        '',
        'Here, time dissolves in the storm\'s embrace,',
        'A dance of chaos, calm, and quiet grace.',
        'The rain, a poet, writes the city\'s soul—',
        'A paradox of modernity and grace.',
        '',
        'So let the storm carve its silent hymn,',
        'A testament to Singapore\'s soul.',
        'In every drop, a story, a dream—',
        'A city where the rain is both a guest and friend.'
    ]
    
    print("🌧️  SINGAPORE RAIN POEM (Typewriter Effect) 🌧️")
    print("=" * 60)
    
    for line in poem_lines:
        for char in line:
            print(char, end='', flush=True)
            time.sleep(0.05)
        print()
        time.sleep(0.3)
    
    print("=" * 60)

if __name__ == "__main__":
    print("Choose display method:")
    print("1. Standard display")
    print("2. Typewriter effect")
    
    choice = input("Enter choice (1 or 2): ").strip()
    
    if choice == "2":
        display_with_typewriter_effect()
    else:
        display_singapore_rain_poem()

